---
version: '3'

services:
  sbhum:
    image: jcostom/sbhum:latest
    container_name: sbhum
    restart: unless-stopped
    environment:
      PLUG_IP: FIXME-IP-ADDR
      LOW: 40
      HIGH: 55
      MIN_RUN_TIME: 900
      SLEEP_TIME: 180
      TOKEN: FIXME-TOKEN
      SECRET: FIXME-SECRET
      DEVID: FIXME-DEVID
      TZ: America/New_York
      INFLUX_BUCKET: FIXME
      INFLUX_ORG: FIXME
      INFLUX_TOKEN: 'FIXME'
      INFLUX_URL: 'http://FIXME:8086/'
      INFLUX_MEASUREMENT: FIXME
    networks:
      - containers

networks:
  containers:
    external: true

# or, if you don't already have that network defined, you could do it in this compose file.
# networks:
#   containers:
#     name: containers
#     driver: bridge
#     attachable: true
#     driver_opts:
#       com.docker.network.bridge.name: br-containers